* This Repository has Moved!

  Due to the fact that GitHub is hosting the files on privately owned
  servers located in the USA, this repository has been moved to
  [[https://codeberg.org/ormf/ox-html-multipage/][Codeberg]] in November of 2025. It
  will not receive further updates or patches. Issues and pull
  requests will not be looked at here either, please submit your
  patches and issue tickets on Codeberg, or send them directly via
  good old email patches to the author.

  Thanks.* ox-html-multipage

** Author

   Orm Finnendahl (c) 2024

** License

   GPL 2.0 or later, see the file LICENSE

   Use at own risk, no warranties whatsoever
   
** Overview

   First attempt to extend org-html-export with multipage support. The
   code has been developed using/extending org 9.8-pre.

   Note that the code is in development and currently destructively
   modifies code of the html backend it is based on.
   
** Installation

   in emacs

   =(load "ox-html.el")=
   =(load "ox.el")=

   Switch to an org buffer to export. The following key binding should
   export to a mutlipage html file located in the =html= subfolder of
   the exported org file.

   =C-c C-e h m=

   
* CLAMPS

  Common Lisp Aided Music Production System

** Overview

   clamps is a system for realtime and non-realtime music production
   written in Common Lisp. It enables a seamless workflow between
   high-level structures to define musical processes all the way down
   to low level dsp definitions for sound creation including browser
   based interfaces for interactive work and control useable for live
   performances. In that respect it combines features of systems like
   OpenMusic, SuperCollider or the Pure Data/Max family of software.

   The components rely on and extend software not written by the
   author. The most important are listed under Dependencies.

** Prerequisites

   - Jack

   - SBCL

   - Quicklisp

   - preferably Emacs & Sly
     
** Dependencies

   - Incudine

     Used for sample accurate scheduling, the definition of the DSP
     parts and realtime IO (Audio, MIDI, OSC...).

   - Common Music (including FOMUS)

     Used as a high level interface for algorithmic composition,
     im/export from/to MIDI, SVG, Notation and realtime output (using
     incudine).

   - CLOG

     Used for browser based interactive GUI definitions.

** Installation