* ox-html-multipage

** Author

   Orm Finnendahl (c) 2024

** License

   GPL 2.0 or later, see the file LICENSE

   Use at own risk, no warranties whatsoever
   
** Overview

   First attempt to extend org-html-export with multipage support. The
   code has been developed on top of org 9.6.15

   Note that the code is in development and currently destructively
   modifies code of the html backend it is based on. This will be
   fixed as soon as the code gets finalized. When running this code,
   single page html export might stop working the way it has worked
   before until the code ha been finalized. In that case it will be
   working again as expected after reloading ox-html.el
   
** Installation

   in emacs

   =(load "ox-html-multipage.el")=

   Switch to an org buffer to export

   Before exporting ensure that a subfolder named "html" in the source
   folder of the org document exists (create it if it doesn't exist).

   =M-x eval-expression <Return> (org-html-export-to-multipage-html) <Return>=
